version: '3.8'

services:
  etcd:
    image: quay.io/coreos/etcd:v3.4.13
    container_name: etcd
    environment:
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_NAME=etcd1
    ports:
      - "2379:2379"
    networks:
      - pg-network

  monitor:
    image: citusdata/pg_auto_failover:demo
    container_name: pg-monitor
    environment:
      PGDATA: /tmp/pgaf
      PG_AUTOCTL_DEBUG: 1
    command: pg_autoctl create monitor --ssl-self-signed --auth trust --run
    depends_on:
      - etcd
    expose:
      - 5432
    networks:
      - pg-network

  postgres-master:
    image: citusdata/pg_auto_failover:demo
    container_name: postgres-master
    environment:
      PGDATA: /tmp/pgaf
      PGUSER: admin
      PGDATABASE: app_db
      PG_AUTOCTL_MONITOR: "postgresql://autoctl_node@monitor/pg_auto_failover"
    command: pg_autoctl create postgres --ssl-self-signed --auth trust --pg-hba-lan --run
    depends_on:
      - monitor
    ports:
      - "5432:5432"
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d app_db"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - pg-network

  postgres-slave1:
    image: citusdata/pg_auto_failover:demo
    container_name: postgres-slave1
    environment:
      PGDATA: /tmp/pgaf
      PGUSER: admin
      PGDATABASE: app_db
      PG_AUTOCTL_MONITOR: "postgresql://autoctl_node@monitor/pg_auto_failover"
    command: pg_autoctl create postgres --ssl-self-signed --auth trust --pg-hba-lan --run
    depends_on:
      postgres-master:
        condition: service_healthy
      monitor:
        condition: service_started
    ports:
      - "5433:5432"
    expose:
      - 5432
    networks:
      - pg-network

  postgres-slave2:
    image: citusdata/pg_auto_failover:demo
    container_name: postgres-slave2
    environment:
      PGDATA: /tmp/pgaf
      PGUSER: admin
      PGDATABASE: app_db
      PG_AUTOCTL_MONITOR: "postgresql://autoctl_node@monitor/pg_auto_failover"
    command: pg_autoctl create postgres --ssl-self-signed --auth trust --pg-hba-lan --run
    depends_on:
      postgres-master:
        condition: service_healthy
      monitor:
        condition: service_started
    ports:
      - "5434:5432"
    expose:
      - 5432
    networks:
      - pg-network

networks:
  pg-network:
    driver: bridge