global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'orders'
    static_configs:
      - targets:
          - orders1:5000
          - orders2:5000

  - job_name: 'users'
    static_configs:
      - targets:
          - users1:5000
          - users2:5000

  - job_name: 'products'
    static_configs:
      - targets:
          - products1:5000
          - products2:5000

  - job_name: 'postgres'
    static_configs:
      - targets:
          - postgres-exporter:9187
